# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recet', '0002_auto_20160212_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='category2',
        ),
        migrations.AddField(
            model_name='receta',
            name='instructions',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
