# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recet', '0003_auto_20160213_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
